CREATE TABLE Planets (name CHAR(20), dist FLOAT, radio FLOAT, grav FLOAT, years FLOAT, temp INT, ring BOOLEAN);
CREATE TABLE Satellites (name CHAR(20), planet CHAR(20), discover CHAR(20), dyear INT);
CREATE TABLE Landings (spaceship CHAR(20), planet CHAR(20), ctry CHAR(20), year INT);
INSERT INTO Planets (name, dist, radio, grav, years, temp, ring) VALUES ('Mercurio', 0.39, 0.38, 2.8, 0.241, 440, FALSE);
INSERT INTO Planets (name, dist, radio, grav, years, temp, ring) VALUES ('Venus', 0.72, 0.95, 8.9, 0.615, 730, FALSE);
INSERT INTO Planets (name, dist, radio, grav, years, temp, ring) VALUES ('Tierra', 1.00, 1.00, 9.8, 1.000, 288, FALSE);
INSERT INTO Planets (name, dist, radio, grav, years, temp, ring) VALUES ('Marte', 1.52, 0.53, 3.7, 1.880, 186, FALSE);
INSERT INTO Planets (name, dist, radio, grav, years, temp, ring) VALUES ('Júpiter', 5.20, 10.97, 22.9, 11.862, 152, TRUE);
INSERT INTO Planets (name, dist, radio, grav, years, temp, ring) VALUES ('Saturno', 9.54, 9.14, 9.1, 29.447, 134, TRUE);
INSERT INTO Planets (name, dist, radio, grav, years, temp, ring) VALUES ('Urano', 19.19, 3.98, 7.8, 84.017, 76, TRUE);
INSERT INTO Planets (name, dist, radio, grav, years, temp, ring) VALUES ('Neptuno', 30.07, 3.86, 11.0, 164.791, 53, TRUE);
INSERT INTO Satellites (name, planet, discover, dyear) VALUES ('Luna', 'Tierra', NULL, NULL);
INSERT INTO Satellites (name, planet, discover, dyear) VALUES ('Ganímedes', 'Júpiter', 'Galileo', 1610);
INSERT INTO Satellites (name, planet, discover, dyear) VALUES ('Calisto', 'Júpiter', 'Galileo', 1610);
INSERT INTO Satellites (name, planet, discover, dyear) VALUES ('Europa', 'Júpiter', 'Galileo', 1610);
INSERT INTO Satellites (name, planet, discover, dyear) VALUES ('Ío', 'Júpiter', 'Galileo', 1610);
INSERT INTO Satellites (name, planet, discover, dyear) VALUES ('Titán', 'Saturno', 'Huygens', 1655);
INSERT INTO Satellites (name, planet, discover, dyear) VALUES ('Triton', 'Neptuno', 'Lassell', 1845);
INSERT INTO Landings (spaceship, planet, ctry, year) VALUES ('Messenger', 'Mercurio', 'EEUU', 2015);
INSERT INTO Landings (spaceship, planet, ctry, year) VALUES ('Venera 3', 'Venus', 'URSS', 1966);
INSERT INTO Landings (spaceship, planet, ctry, year) VALUES ('Pioneer', 'Venus', 'EEUU', 1978);
INSERT INTO Landings (spaceship, planet, ctry, year) VALUES ('Mars 2', 'Marte', 'URSS', 1971);
INSERT INTO Landings (spaceship, planet, ctry, year) VALUES ('Viking 1', 'Marte', 'EEUU', 1976);
INSERT INTO Landings (spaceship, planet, ctry, year) VALUES ('Beagle 2', 'Marte', 'ESA', 2003);
INSERT INTO Landings (spaceship, planet, ctry, year) VALUES ('Galileo', 'Júpiter', 'EEUU', 2003);
